### PR TITLE
fix build on arm

### PR DESCRIPTION
**Pull request by herrernst**
Fix for https://github.com/mvdnes/portaudio-rs/issues/5

### CODE REVIEW

**Comment by mvdnes** [comment]
Does this also work with `as const *u8`? I like to be as explicit as possible when it comes to raw pointer casts.

**Comment by herrernst** [comment]
You mean `as *const u8`, don't you? Otherwise, I get "expected identifier, found keyword `const`".

**Comment by mvdnes** [comment]
Ah yes, that was what I meant.

**Comment by herrernst** [comment]
No. It then compiles on ARM, but not on x64 anymore. If you want to be explicit, maybe you can use a [std::os::raw::c_char](https://doc.rust-lang.org/nightly/std/os/raw/type.c_char.html)?
I've created [another branch](https://github.com/herrernst/portaudio-rs/tree/use-raw-c_char) where I do it, and then it works on arm *and* x64. But I warn you, I really don't know what I am doing! ;)

**Comment by herrernst** [comment]
Okay, `std::os::raw::c_char` is most probably the correct type, as it is [the type that `from_ptr` expects](https://doc.rust-lang.org/nightly/std/ffi/struct.CStr.html#method.from_ptr). I've opened [another pull request with the correct change](https://github.com/mvdnes/portaudio-rs/pull/7).

**Pull request closed without merging**
